import 'fake-indexeddb/auto';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {PDFDocument} from 'pdf-lib';
Object.defineProperty(globalThis,'location',{value:{origin:'https://test.invalid'}});
const {api,remove,importSeller}=await import('./labft-src/test-api');
const id=await importSeller({id:'test1',name:'Vendeur fictif',addr:'Bien fictif',price:200000});
assert.equal(await importSeller({id:'test1',name:'Vendeur fictif'}),id);
let d=await api('/api/dossiers?id='+id);assert.equal(d.data.address,'Bien fictif');assert.equal(d.data.price,'200000');
await api('/api/dossiers',{id,version:d.version,data:d.data});
await assert.rejects(api('/api/dossiers',{id,version:d.version,data:d.data}));
const f=new FormData();f.set('file',new File(['TEST'],'test.txt',{type:'text/plain'}));f.set('dossier',id);f.set('category','Autre');await api('/api/documents',f);
d=await api('/api/dossiers?id='+id);assert.equal(d.documents.length,1);
await assert.rejects(api('/api/check',{id}));await assert.rejects(api('/api/extract',{document:d.documents[0].id}));
const {buildPdf}=await import('./labft-src/lib/pdf');
const bytes=await buildPdf(d,(await api('/api/profile')).profile,d.documents,[],{font:readFileSync('labft-src/public/fonts/montserrat-latin-400-normal.woff'),boldFont:readFileSync('labft-src/public/fonts/montserrat-latin-600-normal.woff'),logo:readFileSync('labft-src/public/logo-tribu-immo.jpeg')});
assert.ok((await PDFDocument.load(bytes)).getPageCount()>0);
await remove('/api/dossiers?id='+id);assert.equal((await api('/api/dossiers')).length,0);
console.log('PASS: import idempotent, fields, local save, version conflict, document upload, unavailable services, PDF generation, delete');
