import {emptyProfile, emptyCase, emptyParty} from './lib/model';
const DB='tribu-cockpit-labft-test-v1';
const dbp=new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{r.result.createObjectStore('cases',{keyPath:'id'});r.result.createObjectStore('docs',{keyPath:'id'});r.result.createObjectStore('profile');};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
async function op(store:string,mode:IDBTransactionMode,fn:(s:IDBObjectStore)=>IDBRequest){const db=await dbp;return new Promise<any>((resolve,reject)=>{const tx=db.transaction(store,mode);const r=fn(tx.objectStore(store));tx.oncomplete=()=>resolve(r.result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
const all=(s:string)=>op(s,'readonly',s=>s.getAll());const get=(s:string,id:string)=>op(s,'readonly',s=>s.get(id));const put=(s:string,v:any)=>op(s,'readwrite',s=>s.put(v));const del=(s:string,id:string)=>op(s,'readwrite',s=>s.delete(id));
export async function api(url:string,body?:any){const u=new URL(url,location.origin);const id=u.searchParams.get('id');
if(u.pathname==='/api/profile'){if(body)await op('profile','readwrite',s=>s.put(body,'me'));return {profile:await get('profile','me')||emptyProfile,user:{name:'Espace de test local',email:''},aiReady:false};}
if(u.pathname==='/api/dossiers'){
 if(body){const prev=body.id?await get('cases',body.id):null;if(body.id&&!prev)throw Error('Dossier introuvable');if(prev&&prev.version!==body.version)throw Error('Dossier modifié dans un autre onglet. Rechargez-le.');const r={id:body.id||crypto.randomUUID(),version:(prev?.version||0)+1,updated:new Date().toISOString(),data:body.data};await put('cases',r);return r;}
 if(!id)return all('cases');const r=await get('cases',id);if(!r)throw Error('Dossier introuvable');const documents=(await all('docs')).filter((d:any)=>d.dossier===id).map((d:any)=>({...d,url:URL.createObjectURL(d.file),file:undefined}));return {...r,documents,checks:[]};}
if(u.pathname==='/api/documents'&&body instanceof FormData){const file=body.get('file') as File;if(!file||file.size>20*1024*1024)throw Error('Pièce limitée à 20 Mo');const r={id:crypto.randomUUID(),dossier:body.get('dossier'),name:file.name,mime:file.type,size:file.size,category:body.get('category'),party:body.get('party'),created:new Date().toISOString(),file};await put('docs',r);return {id:r.id};}
throw Error('Service indisponible en test : aucune analyse IA ni vérification automatique du gel des avoirs effectuée.');}
export async function remove(url:string){const u=new URL(url,location.origin),id=u.searchParams.get('id')!;if(u.pathname==='/api/documents')await del('docs',id);else if(u.pathname==='/api/dossiers'){for(const d of await all('docs'))if(d.dossier===id)await del('docs',d.id);await del('cases',id);}return {ok:true};}
export async function importSeller(s:any){const ref='cockpit-test:'+s.id;const existing=(await all('cases')).find((x:any)=>x.data.reference===ref);if(existing)return existing.id;const data=emptyCase('TEST — '+(s.nom||s.name||'Dossier vendeur'));data.reference=ref;data.address=s.adresse||s.address||s.addr||'';data.price=String(s.prix||s.price||'');const p=emptyParty();p.name=s.nom||s.name||'';data.parties=[p];return (await api('/api/dossiers',{data})).id;}
