import { z } from 'zod';
const str=z.string().max(4000).default('');
export const partySchema=z.object({id:z.string().uuid(),role:z.enum(['Vendeur','Acquéreur','Bénéficiaire effectif','Représentant','Autre intervenant']),kind:z.enum(['Personne physique','Personne morale']),name:str,firstName:str,birthDate:str,birthPlace:str,nationality:str,address:str,postcode:str,profession:str,registration:str,representative:str,activity:str,function:str,salary:str,income:str,loans:str,aliases:str});
export const caseSchema=z.object({title:z.string().min(1).max(200),reference:str,address:str,price:str,fees:str,feesPayer:str,occupation:str,mainResidence:str,since:str,reinvest:str,reason:str,savings:str,donation:str,reinvested:str,otherFunds:str,bank:str,loanAmount:str,loanDuration:str,foreignFunds:str,observations:str,decision:str,parties:z.array(partySchema).max(40),answers:z.record(z.enum(['Oui','Non','Non applicable'])),validated:z.boolean().default(false)});
export const profileSchema=z.object({name:str,firstName:str,email:z.string().max(300).default(''),phone:str,status:str,rsac:str,city:str});
export type CaseData=z.infer<typeof caseSchema>; export type Party=z.infer<typeof partySchema>;export type Profile=z.infer<typeof profileSchema>;
export const partyFields:Record<string,string>={name:'Nom / dénomination sociale',firstName:'Prénom(s)',birthDate:'Date de naissance',birthPlace:'Lieu de naissance',nationality:'Nationalité',address:'Adresse / siège social',postcode:'Code postal',profession:'Profession',registration:'Lieu et numéro d’immatriculation',representative:'Représentée par',activity:'Activité de l’entreprise',function:'Fonction / qualité',salary:'Salaire net mensuel (€)',income:'Autres revenus mensuels (€)',loans:'Emprunts en cours mensuels (€)',aliases:'Autres noms / nom d’usage'};
export const operationFields:Record<string,string>={reference:'Référence du mandat',address:'Adresse du bien',price:'Prix de vente (€)',fees:'Honoraires TTC (€)',feesPayer:'Honoraires à la charge de',occupation:'Occupation du bien',mainResidence:'Résidence principale du vendeur',since:'Depuis le',reinvest:'Réinvestissement en résidence principale',reason:'Motif de la cession',savings:'Épargne : montant et provenance',donation:'Donation / succession : montant et provenance',reinvested:'Prix de vente réinvesti',otherFunds:'Autres fonds : montant et provenance',bank:'Nom de la banque',loanAmount:'Montant du prêt (€)',loanDuration:'Durée du prêt',foreignFunds:'Fonds étrangers : pays, banque et provenance',observations:'Observations sur l’opération',decision:'Synthèse et suites données par le conseiller'};
export function emptyCase(title:string):CaseData{return caseSchema.parse({title,parties:[],answers:{}})}
export function emptyParty():Party{return partySchema.parse({id:crypto.randomUUID(),role:'Vendeur',kind:'Personne physique'})}
export const emptyProfile=profileSchema.parse({});
export function identity(p:Party){return JSON.stringify([p.id,p.name,p.firstName,p.birthDate,p.birthPlace,p.nationality,p.aliases,p.kind])}
